docker-node: &node
  image: circleci/node:8.11-stretch
  environment:
    DATABASE_URI: postgresql://ci@localhost/scaffolding_test

docker-postgres: &db
  image: circleci/postgres:9.6-alpine-postgis-ram
  environment:
    POSTGRES_DB: scaffolding_test
    POSTGRES_USER: ci
    POSTGRES_PASSWORD: ""

version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - <<: *node
      - <<: *db
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Lint, compile and run migrations
          command: |
            npm run lint
            npm run compile
            npm run sequelize db:migrate

      - run:
          name: Test
          command: |
            npm test
